version: "3.7"
services:
  dbpostgresql:
    image: postgres:11-alpine
    container_name: database
    volumes:
      - db-java-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=exchange
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

  et-api:
    image: pkwasek/et-api:5.2
    container_name: et-api
    depends_on:
      - dbpostgresql
    ports:
      - 8080:8080

  et-app:
    image: pkwasek/et-angular-app:5.2
    container_name: et-app-angular
    ports:
      - 4200:80

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - 3000:3000

volumes:
  db-java-data:
