version: "3.7"
services:
  dbpostgresql:
    image: postgres:11-alpine
    volumes:
      - db-java-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=exchange
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

  et-api:
    image: pkwasek/et-api:5.1
    depends_on:
      - dbpostgresql
    ports:
      - 8080:8080

  et-app:
    image: pkwasek/et-angular-app:5.1
    container_name: et-app-angular
    ports:
      - 4200:80

volumes:
  db-java-data:
